Mon Mar 17 12:30:04 CET 2003
Removing files from previous runs
rmsd.dat not found
STO FACENDO LA PROTEINA: protein0.pdb
Reading protein.pdb...
Read 1454 atoms
Analyzing pdb file
There are 1 chains and 0 blocks of water and 188 residues with 1454 atoms

  chain  #res #atoms
  1 ' '   188   1454  


Select the Force Field:
 0: Gromacs Forcefield (see manual)
 1: Gromacs Forcefield with all hydrogens (proteins only)
 2: GROMOS96 43a1 Forcefield (official distribution)
 3: GROMOS96 43b1 Vacuum Forcefield (official distribution)
 4: GROMOS96 43a2 Forcefield (development) (improved alkane dihedrals)
 5: OPLS-AA/L all-atom force field (2001 aminoacid dihedrals)
Using ffgmx2 force field
Reading residue database... (ffgmx2)
Processing chain 1 (1454 atoms, 188 residues)
Checking for duplicate atoms....
deleting duplicate atom    O  PRO 188  pdb nr 2875
Now there are 1453 atoms
N-terminus: NH3+
C-terminus: COO-
Now there are 188 residues with 2875 atoms
Reading protein.pdb...
Read 1454 atoms
Analyzing pdb file
There are 1 chains and 0 blocks of water and 188 residues with 1454 atoms

  chain  #res #atoms
  1 ' '   188   1454  


Select the Force Field:
 0: Gromacs Forcefield (see manual)
 1: Gromacs Forcefield with all hydrogens (proteins only)
 2: GROMOS96 43a1 Forcefield (official distribution)
 3: GROMOS96 43b1 Vacuum Forcefield (official distribution)
 4: GROMOS96 43a2 Forcefield (development) (improved alkane dihedrals)
 5: OPLS-AA/L all-atom force field (2001 aminoacid dihedrals)
Using ffgmx2 force field
Reading residue database... (ffgmx2)
Processing chain 1 (1454 atoms, 188 residues)
Checking for duplicate atoms....
deleting duplicate atom    O  PRO 188  pdb nr 2875
Now there are 1453 atoms
N-terminus: NH3+
C-terminus: COO-
Now there are 188 residues with 2875 atoms
protein built
Removing files from previous runs
sasa.out not found
rmsd.out not found
phinrg_a.out not found
phinrg_w.out not found
There are 188 residues
protein calc'd
output analysed
STO FACENDO LA PROTEINA: protein1.pdb
Reading protein.pdb...
Read 1454 atoms
Analyzing pdb file
There are 1 chains and 0 blocks of water and 188 residues with 1454 atoms

  chain  #res #atoms
  1 ' '   188   1454  


Select the Force Field:
 0: Gromacs Forcefield (see manual)
 1: Gromacs Forcefield with all hydrogens (proteins only)
 2: GROMOS96 43a1 Forcefield (official distribution)
 3: GROMOS96 43b1 Vacuum Forcefield (official distribution)
 4: GROMOS96 43a2 Forcefield (development) (improved alkane dihedrals)
 5: OPLS-AA/L all-atom force field (2001 aminoacid dihedrals)
Using ffgmx2 force field
Reading residue database... (ffgmx2)
Processing chain 1 (1454 atoms, 188 residues)
Checking for duplicate atoms....
deleting duplicate atom    O  PRO 188  pdb nr 2875
Now there are 1453 atoms
N-terminus: NH3+
C-terminus: COO-
Now there are 188 residues with 2875 atoms
Reading protein.pdb...
Read 1454 atoms
Analyzing pdb file
There are 1 chains and 0 blocks of water and 188 residues with 1454 atoms

  chain  #res #atoms
  1 ' '   188   1454  


Select the Force Field:
 0: Gromacs Forcefield (see manual)
 1: Gromacs Forcefield with all hydrogens (proteins only)
 2: GROMOS96 43a1 Forcefield (official distribution)
 3: GROMOS96 43b1 Vacuum Forcefield (official distribution)
 4: GROMOS96 43a2 Forcefield (development) (improved alkane dihedrals)
 5: OPLS-AA/L all-atom force field (2001 aminoacid dihedrals)
Using ffgmx2 force field
Reading residue database... (ffgmx2)
Processing chain 1 (1454 atoms, 188 residues)
Checking for duplicate atoms....
deleting duplicate atom    O  PRO 188  pdb nr 2875
Now there are 1453 atoms
N-terminus: NH3+
C-terminus: COO-
Now there are 188 residues with 2875 atoms
protein built
Removing files from previous runs
sasa.out not found
rmsd.out not found
phinrg_a.out not found
phinrg_w.out not found
There are 188 residues
protein calc'd
output analysed
STO FACENDO LA PROTEINA: protein2.pdb
Reading protein.pdb...
Read 1454 atoms
Analyzing pdb file
There are 1 chains and 0 blocks of water and 188 residues with 1454 atoms

  chain  #res #atoms
  1 ' '   188   1454  


Select the Force Field:
 0: Gromacs Forcefield (see manual)
 1: Gromacs Forcefield with all hydrogens (proteins only)
 2: GROMOS96 43a1 Forcefield (official distribution)
 3: GROMOS96 43b1 Vacuum Forcefield (official distribution)
 4: GROMOS96 43a2 Forcefield (development) (improved alkane dihedrals)
 5: OPLS-AA/L all-atom force field (2001 aminoacid dihedrals)
Using ffgmx2 force field
Reading residue database... (ffgmx2)
Processing chain 1 (1454 atoms, 188 residues)
Checking for duplicate atoms....
deleting duplicate atom    O  PRO 188  pdb nr 2875
Now there are 1453 atoms
N-terminus: NH3+
C-terminus: COO-
Now there are 188 residues with 2875 atoms
Reading protein.pdb...
Read 1454 atoms
Analyzing pdb file
There are 1 chains and 0 blocks of water and 188 residues with 1454 atoms

  chain  #res #atoms
  1 ' '   188   1454  


Select the Force Field:
 0: Gromacs Forcefield (see manual)
 1: Gromacs Forcefield with all hydrogens (proteins only)
 2: GROMOS96 43a1 Forcefield (official distribution)
 3: GROMOS96 43b1 Vacuum Forcefield (official distribution)
 4: GROMOS96 43a2 Forcefield (development) (improved alkane dihedrals)
 5: OPLS-AA/L all-atom force field (2001 aminoacid dihedrals)
Using ffgmx2 force field
Reading residue database... (ffgmx2)
Processing chain 1 (1454 atoms, 188 residues)
Checking for duplicate atoms....
deleting duplicate atom    O  PRO 188  pdb nr 2875
Now there are 1453 atoms
N-terminus: NH3+
C-terminus: COO-
Now there are 188 residues with 2875 atoms
protein built
Removing files from previous runs
sasa.out not found
rmsd.out not found
phinrg_a.out not found
phinrg_w.out not found
There are 188 residues
protein calc'd
output analysed
STO FACENDO LA PROTEINA: protein3.pdb
Reading protein.pdb...
Read 1454 atoms
Analyzing pdb file
There are 1 chains and 0 blocks of water and 188 residues with 1454 atoms

  chain  #res #atoms
  1 ' '   188   1454  


Select the Force Field:
 0: Gromacs Forcefield (see manual)
 1: Gromacs Forcefield with all hydrogens (proteins only)
 2: GROMOS96 43a1 Forcefield (official distribution)
 3: GROMOS96 43b1 Vacuum Forcefield (official distribution)
 4: GROMOS96 43a2 Forcefield (development) (improved alkane dihedrals)
 5: OPLS-AA/L all-atom force field (2001 aminoacid dihedrals)
Using ffgmx2 force field
Reading residue database... (ffgmx2)
Processing chain 1 (1454 atoms, 188 residues)
Checking for duplicate atoms....
deleting duplicate atom    O  PRO 188  pdb nr 2875
Now there are 1453 atoms
N-terminus: NH3+
C-terminus: COO-
Now there are 188 residues with 2875 atoms
Reading protein.pdb...
Read 1454 atoms
Analyzing pdb file
There are 1 chains and 0 blocks of water and 188 residues with 1454 atoms

  chain  #res #atoms
  1 ' '   188   1454  


Select the Force Field:
 0: Gromacs Forcefield (see manual)
 1: Gromacs Forcefield with all hydrogens (proteins only)
 2: GROMOS96 43a1 Forcefield (official distribution)
 3: GROMOS96 43b1 Vacuum Forcefield (official distribution)
 4: GROMOS96 43a2 Forcefield (development) (improved alkane dihedrals)
 5: OPLS-AA/L all-atom force field (2001 aminoacid dihedrals)
Using ffgmx2 force field
Reading residue database... (ffgmx2)
Processing chain 1 (1454 atoms, 188 residues)
Checking for duplicate atoms....
deleting duplicate atom    O  PRO 188  pdb nr 2875
Now there are 1453 atoms
N-terminus: NH3+
C-terminus: COO-
Now there are 188 residues with 2875 atoms
protein built
Removing files from previous runs
sasa.out not found
rmsd.out not found
phinrg_a.out not found
phinrg_w.out not found
There are 188 residues
protein calc'd
output analysed
STO FACENDO LA PROTEINA: protein4.pdb
Reading protein.pdb...
Read 1454 atoms
Analyzing pdb file
There are 1 chains and 0 blocks of water and 188 residues with 1454 atoms

  chain  #res #atoms
  1 ' '   188   1454  


Select the Force Field:
 0: Gromacs Forcefield (see manual)
 1: Gromacs Forcefield with all hydrogens (proteins only)
 2: GROMOS96 43a1 Forcefield (official distribution)
 3: GROMOS96 43b1 Vacuum Forcefield (official distribution)
 4: GROMOS96 43a2 Forcefield (development) (improved alkane dihedrals)
 5: OPLS-AA/L all-atom force field (2001 aminoacid dihedrals)
Using ffgmx2 force field
Reading residue database... (ffgmx2)
Processing chain 1 (1454 atoms, 188 residues)
Checking for duplicate atoms....
deleting duplicate atom    O  PRO 188  pdb nr 2875
Now there are 1453 atoms
N-terminus: NH3+
C-terminus: COO-
Now there are 188 residues with 2875 atoms
Reading protein.pdb...
Read 1454 atoms
Analyzing pdb file
There are 1 chains and 0 blocks of water and 188 residues with 1454 atoms

  chain  #res #atoms
  1 ' '   188   1454  


Select the Force Field:
 0: Gromacs Forcefield (see manual)
 1: Gromacs Forcefield with all hydrogens (proteins only)
 2: GROMOS96 43a1 Forcefield (official distribution)
 3: GROMOS96 43b1 Vacuum Forcefield (official distribution)
 4: GROMOS96 43a2 Forcefield (development) (improved alkane dihedrals)
 5: OPLS-AA/L all-atom force field (2001 aminoacid dihedrals)
Using ffgmx2 force field
Reading residue database... (ffgmx2)
Processing chain 1 (1454 atoms, 188 residues)
Checking for duplicate atoms....
deleting duplicate atom    O  PRO 188  pdb nr 2875
Now there are 1453 atoms
N-terminus: NH3+
C-terminus: COO-
Now there are 188 residues with 2875 atoms
protein built
Removing files from previous runs
sasa.out not found
rmsd.out not found
phinrg_a.out not found
phinrg_w.out not found
There are 188 residues
protein calc'd
output analysed
STO FACENDO LA PROTEINA: protein5.pdb
Reading protein.pdb...
Read 1454 atoms
Analyzing pdb file
There are 1 chains and 0 blocks of water and 188 residues with 1454 atoms

  chain  #res #atoms
  1 ' '   188   1454  


Select the Force Field:
 0: Gromacs Forcefield (see manual)
 1: Gromacs Forcefield with all hydrogens (proteins only)
 2: GROMOS96 43a1 Forcefield (official distribution)
 3: GROMOS96 43b1 Vacuum Forcefield (official distribution)
 4: GROMOS96 43a2 Forcefield (development) (improved alkane dihedrals)
 5: OPLS-AA/L all-atom force field (2001 aminoacid dihedrals)
Using ffgmx2 force field
Reading residue database... (ffgmx2)
Processing chain 1 (1454 atoms, 188 residues)
Checking for duplicate atoms....
deleting duplicate atom    O  PRO 188  pdb nr 2875
Now there are 1453 atoms
N-terminus: NH3+
C-terminus: COO-
Now there are 188 residues with 2875 atoms
Reading protein.pdb...
Read 1454 atoms
Analyzing pdb file
There are 1 chains and 0 blocks of water and 188 residues with 1454 atoms

  chain  #res #atoms
  1 ' '   188   1454  


Select the Force Field:
 0: Gromacs Forcefield (see manual)
 1: Gromacs Forcefield with all hydrogens (proteins only)
 2: GROMOS96 43a1 Forcefield (official distribution)
 3: GROMOS96 43b1 Vacuum Forcefield (official distribution)
 4: GROMOS96 43a2 Forcefield (development) (improved alkane dihedrals)
 5: OPLS-AA/L all-atom force field (2001 aminoacid dihedrals)
Using ffgmx2 force field
Reading residue database... (ffgmx2)
Processing chain 1 (1454 atoms, 188 residues)
Checking for duplicate atoms....
deleting duplicate atom    O  PRO 188  pdb nr 2875
Now there are 1453 atoms
N-terminus: NH3+
C-terminus: COO-
Now there are 188 residues with 2875 atoms
protein built
Removing files from previous runs
sasa.out not found
rmsd.out not found
phinrg_a.out not found
phinrg_w.out not found
There are 188 residues
protein calc'd
output analysed
STO FACENDO LA PROTEINA: protein6.pdb
Reading protein.pdb...
Read 1454 atoms
Analyzing pdb file
There are 1 chains and 0 blocks of water and 188 residues with 1454 atoms

  chain  #res #atoms
  1 ' '   188   1454  


Select the Force Field:
 0: Gromacs Forcefield (see manual)
 1: Gromacs Forcefield with all hydrogens (proteins only)
 2: GROMOS96 43a1 Forcefield (official distribution)
 3: GROMOS96 43b1 Vacuum Forcefield (official distribution)
 4: GROMOS96 43a2 Forcefield (development) (improved alkane dihedrals)
 5: OPLS-AA/L all-atom force field (2001 aminoacid dihedrals)
Using ffgmx2 force field
Reading residue database... (ffgmx2)
Processing chain 1 (1454 atoms, 188 residues)
Checking for duplicate atoms....
deleting duplicate atom    O  PRO 188  pdb nr 2875
Now there are 1453 atoms
N-terminus: NH3+
C-terminus: COO-
Now there are 188 residues with 2875 atoms
Reading protein.pdb...
Read 1454 atoms
Analyzing pdb file
There are 1 chains and 0 blocks of water and 188 residues with 1454 atoms

  chain  #res #atoms
  1 ' '   188   1454  


Select the Force Field:
 0: Gromacs Forcefield (see manual)
 1: Gromacs Forcefield with all hydrogens (proteins only)
 2: GROMOS96 43a1 Forcefield (official distribution)
 3: GROMOS96 43b1 Vacuum Forcefield (official distribution)
 4: GROMOS96 43a2 Forcefield (development) (improved alkane dihedrals)
 5: OPLS-AA/L all-atom force field (2001 aminoacid dihedrals)
Using ffgmx2 force field
Reading residue database... (ffgmx2)
Processing chain 1 (1454 atoms, 188 residues)
Checking for duplicate atoms....
deleting duplicate atom    O  PRO 188  pdb nr 2875
Now there are 1453 atoms
N-terminus: NH3+
C-terminus: COO-
Now there are 188 residues with 2875 atoms
protein built
Removing files from previous runs
sasa.out not found
rmsd.out not found
phinrg_a.out not found
phinrg_w.out not found
There are 188 residues
protein calc'd
output analysed
STO FACENDO LA PROTEINA: protein7.pdb
Reading protein.pdb...
Read 1454 atoms
Analyzing pdb file
There are 1 chains and 0 blocks of water and 188 residues with 1454 atoms

  chain  #res #atoms
  1 ' '   188   1454  


Select the Force Field:
 0: Gromacs Forcefield (see manual)
 1: Gromacs Forcefield with all hydrogens (proteins only)
 2: GROMOS96 43a1 Forcefield (official distribution)
 3: GROMOS96 43b1 Vacuum Forcefield (official distribution)
 4: GROMOS96 43a2 Forcefield (development) (improved alkane dihedrals)
 5: OPLS-AA/L all-atom force field (2001 aminoacid dihedrals)
Using ffgmx2 force field
Reading residue database... (ffgmx2)
Processing chain 1 (1454 atoms, 188 residues)
Checking for duplicate atoms....
deleting duplicate atom    O  PRO 188  pdb nr 2875
Now there are 1453 atoms
N-terminus: NH3+
C-terminus: COO-
Now there are 188 residues with 2875 atoms
Reading protein.pdb...
Read 1454 atoms
Analyzing pdb file
There are 1 chains and 0 blocks of water and 188 residues with 1454 atoms

  chain  #res #atoms
  1 ' '   188   1454  


Select the Force Field:
 0: Gromacs Forcefield (see manual)
 1: Gromacs Forcefield with all hydrogens (proteins only)
 2: GROMOS96 43a1 Forcefield (official distribution)
 3: GROMOS96 43b1 Vacuum Forcefield (official distribution)
 4: GROMOS96 43a2 Forcefield (development) (improved alkane dihedrals)
 5: OPLS-AA/L all-atom force field (2001 aminoacid dihedrals)
Using ffgmx2 force field
Reading residue database... (ffgmx2)
Processing chain 1 (1454 atoms, 188 residues)
Checking for duplicate atoms....
deleting duplicate atom    O  PRO 188  pdb nr 2875
Now there are 1453 atoms
N-terminus: NH3+
C-terminus: COO-
Now there are 188 residues with 2875 atoms
protein built
Removing files from previous runs
sasa.out not found
rmsd.out not found
phinrg_a.out not found
phinrg_w.out not found
There are 188 residues
protein calc'd
output analysed
STO FACENDO LA PROTEINA: protein8.pdb
Reading protein.pdb...
Read 1454 atoms
Analyzing pdb file
There are 1 chains and 0 blocks of water and 188 residues with 1454 atoms

  chain  #res #atoms
  1 ' '   188   1454  


Select the Force Field:
 0: Gromacs Forcefield (see manual)
 1: Gromacs Forcefield with all hydrogens (proteins only)
 2: GROMOS96 43a1 Forcefield (official distribution)
 3: GROMOS96 43b1 Vacuum Forcefield (official distribution)
 4: GROMOS96 43a2 Forcefield (development) (improved alkane dihedrals)
 5: OPLS-AA/L all-atom force field (2001 aminoacid dihedrals)
Using ffgmx2 force field
Reading residue database... (ffgmx2)
Processing chain 1 (1454 atoms, 188 residues)
Checking for duplicate atoms....
deleting duplicate atom    O  PRO 188  pdb nr 2875
Now there are 1453 atoms
N-terminus: NH3+
C-terminus: COO-
Now there are 188 residues with 2875 atoms
Reading protein.pdb...
Read 1454 atoms
Analyzing pdb file
There are 1 chains and 0 blocks of water and 188 residues with 1454 atoms

  chain  #res #atoms
  1 ' '   188   1454  


Select the Force Field:
 0: Gromacs Forcefield (see manual)
 1: Gromacs Forcefield with all hydrogens (proteins only)
 2: GROMOS96 43a1 Forcefield (official distribution)
 3: GROMOS96 43b1 Vacuum Forcefield (official distribution)
 4: GROMOS96 43a2 Forcefield (development) (improved alkane dihedrals)
 5: OPLS-AA/L all-atom force field (2001 aminoacid dihedrals)
Using ffgmx2 force field
Reading residue database... (ffgmx2)
Processing chain 1 (1454 atoms, 188 residues)
Checking for duplicate atoms....
deleting duplicate atom    O  PRO 188  pdb nr 2875
Now there are 1453 atoms
N-terminus: NH3+
C-terminus: COO-
Now there are 188 residues with 2875 atoms
protein built
Removing files from previous runs
sasa.out not found
rmsd.out not found
phinrg_a.out not found
phinrg_w.out not found
There are 188 residues
protein calc'd
output analysed
STO FACENDO LA PROTEINA: protein9.pdb
Reading protein.pdb...
Read 1454 atoms
Analyzing pdb file
There are 1 chains and 0 blocks of water and 188 residues with 1454 atoms

  chain  #res #atoms
  1 ' '   188   1454  


Select the Force Field:
 0: Gromacs Forcefield (see manual)
 1: Gromacs Forcefield with all hydrogens (proteins only)
 2: GROMOS96 43a1 Forcefield (official distribution)
 3: GROMOS96 43b1 Vacuum Forcefield (official distribution)
 4: GROMOS96 43a2 Forcefield (development) (improved alkane dihedrals)
 5: OPLS-AA/L all-atom force field (2001 aminoacid dihedrals)
Using ffgmx2 force field
Reading residue database... (ffgmx2)
Processing chain 1 (1454 atoms, 188 residues)
Checking for duplicate atoms....
deleting duplicate atom    O  PRO 188  pdb nr 2875
Now there are 1453 atoms
N-terminus: NH3+
C-terminus: COO-
Now there are 188 residues with 2875 atoms
Reading protein.pdb...
Read 1454 atoms
Analyzing pdb file
There are 1 chains and 0 blocks of water and 188 residues with 1454 atoms

  chain  #res #atoms
  1 ' '   188   1454  


Select the Force Field:
 0: Gromacs Forcefield (see manual)
 1: Gromacs Forcefield with all hydrogens (proteins only)
 2: GROMOS96 43a1 Forcefield (official distribution)
 3: GROMOS96 43b1 Vacuum Forcefield (official distribution)
 4: GROMOS96 43a2 Forcefield (development) (improved alkane dihedrals)
 5: OPLS-AA/L all-atom force field (2001 aminoacid dihedrals)
Using ffgmx2 force field
Reading residue database... (ffgmx2)
Processing chain 1 (1454 atoms, 188 residues)
Checking for duplicate atoms....
deleting duplicate atom    O  PRO 188  pdb nr 2875
Now there are 1453 atoms
N-terminus: NH3+
C-terminus: COO-
Now there are 188 residues with 2875 atoms
protein built
Removing files from previous runs
sasa.out not found
rmsd.out not found
phinrg_a.out not found
phinrg_w.out not found
There are 188 residues
protein calc'd
output analysed
STO FACENDO LA PROTEINA: protein10.pdb
Reading protein.pdb...
Read 1454 atoms
Analyzing pdb file
There are 1 chains and 0 blocks of water and 188 residues with 1454 atoms

  chain  #res #atoms
  1 ' '   188   1454  


Select the Force Field:
 0: Gromacs Forcefield (see manual)
 1: Gromacs Forcefield with all hydrogens (proteins only)
 2: GROMOS96 43a1 Forcefield (official distribution)
 3: GROMOS96 43b1 Vacuum Forcefield (official distribution)
 4: GROMOS96 43a2 Forcefield (development) (improved alkane dihedrals)
 5: OPLS-AA/L all-atom force field (2001 aminoacid dihedrals)
Using ffgmx2 force field
Reading residue database... (ffgmx2)
Processing chain 1 (1454 atoms, 188 residues)
Checking for duplicate atoms....
deleting duplicate atom    O  PRO 188  pdb nr 2875
Now there are 1453 atoms
N-terminus: NH3+
C-terminus: COO-
Now there are 188 residues with 2875 atoms
Reading protein.pdb...
Read 1454 atoms
Analyzing pdb file
There are 1 chains and 0 blocks of water and 188 residues with 1454 atoms

  chain  #res #atoms
  1 ' '   188   1454  


Select the Force Field:
 0: Gromacs Forcefield (see manual)
 1: Gromacs Forcefield with all hydrogens (proteins only)
 2: GROMOS96 43a1 Forcefield (official distribution)
 3: GROMOS96 43b1 Vacuum Forcefield (official distribution)
 4: GROMOS96 43a2 Forcefield (development) (improved alkane dihedrals)
 5: OPLS-AA/L all-atom force field (2001 aminoacid dihedrals)
Using ffgmx2 force field
Reading residue database... (ffgmx2)
Processing chain 1 (1454 atoms, 188 residues)
Checking for duplicate atoms....
deleting duplicate atom    O  PRO 188  pdb nr 2875
Now there are 1453 atoms
N-terminus: NH3+
C-terminus: COO-
Now there are 188 residues with 2875 atoms
protein built
Removing files from previous runs
sasa.out not found
rmsd.out not found
phinrg_a.out not found
phinrg_w.out not found
There are 188 residues
protein calc'd
output analysed
